CustomLocalization.AddLocalization( SystemData.Settings.Language.LANGUAGE_ENU, "SkinDefault", L"Skin Default" )
CustomLocalization.AddLocalization( SystemData.Settings.Language.LANGUAGE_ENU, "NoteRequiresUIReload", L"Note: Required UI Reload" )
CustomLocalization.AddLocalization( SystemData.Settings.Language.LANGUAGE_ENU, "ECDefaultsFont", L"Enhanced Client Default Fonts" )
CustomLocalization.AddLocalization( SystemData.Settings.Language.LANGUAGE_ENU, "DefaultNormalFont", L"Normal" )
CustomLocalization.AddLocalization( SystemData.Settings.Language.LANGUAGE_ENU, "DefaultBoldFont", L"Bold" )
CustomLocalization.AddLocalization( SystemData.Settings.Language.LANGUAGE_ENU, "DefaultTitleFont", L"Title" )
CustomLocalization.AddLocalization( SystemData.Settings.Language.LANGUAGE_ENU, "DefaultChatFont", L"Chat" )
CustomLocalization.AddLocalization( SystemData.Settings.Language.LANGUAGE_ENU, "DefaultStatsFont", L"Stats" )
CustomLocalization.AddLocalization( SystemData.Settings.Language.LANGUAGE_ENU, "DefaultNameFont", L"Name" )
CustomLocalization.AddLocalization( SystemData.Settings.Language.LANGUAGE_ENU, "FontPreviewText", L"ABCDEFG abcdefg 1234567890-= !@#$%^&*()_+" )
CustomLocalization.AddLocalization( SystemData.Settings.Language.LANGUAGE_ENU, "UnknownFont", L"(LOCALIZATION MISSING)" )
CustomLocalization.AddLocalization( SystemData.Settings.Language.LANGUAGE_ENU, "SkinDefaultNotSet", L"Skin Default (Not Set)" )

