CustomLocalization.AddLocalization( SystemData.Settings.Language.LANGUAGE_ENU, "ItemPropertySettings", L"Tooltips" )
CustomLocalization.AddLocalization( SystemData.Settings.Language.LANGUAGE_ENU, "TooltipTitleFontSetting", L"Tooltip Title" )
CustomLocalization.AddLocalization( SystemData.Settings.Language.LANGUAGE_ENU, "TooltipBodyFontSetting", L"Tooltip Body" )
CustomLocalization.AddLocalization( SystemData.Settings.Language.LANGUAGE_ENU, "UseItemPropertiesColoring", L"Add coloring to Item Properties" )
CustomLocalization.AddLocalization( SystemData.Settings.Language.LANGUAGE_ENU, "UseItemPropertiesEvaluator", L"Use Item Properties Evaluator" )
CustomLocalization.AddLocalization( SystemData.Settings.Language.LANGUAGE_ENU, "UseItemPropertiesEvaluatorColor", L"Use Evaluator Coloring for High Intensity (requires Use Item Properties Evaluator)" )
